services:
  redis:
    image: redis:7.0
    restart: always

  db:
    image: mariadb:11.4
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - 'db-data:/var/lib/mysql:Z'
      - './db-entrypoint.sql:/docker-entrypoint-initdb.d/db-entrypoint.sql'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    
  celery:
    build: ./site
    stdin_open: true
    env_file:
      - .env
    command: celery -A dmoj_celery worker
    depends_on:
      - redis

  site:
    build: ./site
    restart: always
    stdin_open: true
    env_file:
      - .env
    volumes:
      - './setup-db.sh:/setup-db.sh'
    command: /setup-db.sh
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "localhost:8000"]
      start_period: 5s
      interval: 20s
      timeout: 5s
      retries: 20
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      celery:
        condition: service_started

  bridged:
    build: ./site
    restart: always
    stdin_open: true
    env_file:
      - .env
    command: python3 manage.py runbridged
    depends_on:
      site:
        condition: service_healthy

  judge1:
    build: ./judge
    restart: always
    volumes:
      - ./problems:/problems
    cap_add:
      - SYS_PTRACE
    command: run -c /problems/judge.yml bridged ${JUDGE_NAME1} ${JUDGE_KEY}
    depends_on:
      - bridged

  judge2:
    build: ./judge
    restart: always
    volumes:
      - ./problems:/problems
    cap_add:
      - SYS_PTRACE
    command: run -c /problems/judge.yml bridged ${JUDGE_NAME2} ${JUDGE_KEY}
    depends_on:
      - bridged

  judge3:
    build: ./judge
    restart: always
    volumes:
      - ./problems:/problems
    cap_add:
      - SYS_PTRACE
    command: run -c /problems/judge.yml bridged ${JUDGE_NAME3} ${JUDGE_KEY}
    depends_on:
      - bridged
  judge4:
    build: ./judge
    restart: always
    volumes:
      - ./problems:/problems
    cap_add:
      - SYS_PTRACE
    command: run -c /problems/judge.yml bridged ${JUDGE_NAME4} ${JUDGE_KEY}
    depends_on:
      - bridged
  judge5:
    build: ./judge
    restart: always
    volumes:
      - ./problems:/problems
    cap_add:
      - SYS_PTRACE
    command: run -c /problems/judge.yml bridged ${JUDGE_NAME5} ${JUDGE_KEY}
    depends_on:
      - bridged
  judge6:
    build: ./judge
    restart: always
    volumes:
      - ./problems:/problems
    cap_add:
      - SYS_PTRACE
    command: run -c /problems/judge.yml bridged ${JUDGE_NAME6} ${JUDGE_KEY}
    depends_on:
      - bridged
volumes:
  db-data: